name: "Build"

on:
  push

permissions:
  contents: 'read'
  id-token: 'write'



jobs:
  packaging:
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1, 8.2]
        composer: [2]
    runs-on: ubuntu-latest
    name: "Compose v${{ matrix.composer }} @ PHP ${{ matrix.php }}"
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - name: Login to GitHub Container Registry
        uses: 'docker/login-action@v1'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_REPOSITORY_TOKEN }}

      - name: Process builder
        shell: bash
        run: |
          echo "build_version=preprod" >> $GITHUB_ENV
          echo "build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Set up Depot CLI
        uses: 'depot/setup-action@v1'

      - name: Build and Push Package
        uses: 'depot/build-push-action@v1'
        with:
          project: ${{ secrets.DEPOT_PROJECT_ID }}
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          push: true
          tags: ghcr.io/devgine/composer-php:v${{ matrix.composer }}-php${{ matrix.php }}
          context: .
          file: ./Dockerfile
          build-args: |
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ env.build_date }}
            BUILD_VERSION=v${{ matrix.composer }}-php${{ matrix.php }}
            PHP_VERSION={{ matrix.php }}
            COMPOSER_VERSION=${{ matrix.composer }}

  components:
    needs: packaging
    runs-on: ubuntu-latest
    name: "Components versions"
    container:
      image: ghcr.io/devgine/composer-php:v${{ matrix.composer }}-php${{ matrix.php }}
    steps:
      - name: Composer
        run: composer --version

      - name: PHP
        run: php --version

      - name: PHP Unit
        run: simple-phpunit --version

      - name: Rector
        run: rector -V

      - name: PHPStan
        run: phpstan --version

      - name: PHP Code Standard Fixer
        run: php-cs-fixer --version

      - name: PHP Mess Detector
        run: phpmd --version

      - name: PHP Copy Past Detector
        run: phpcpd --version
