name: "Build"

on:
  push

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  packaging:
    runs-on: ubuntu-latest
    name: "Composer PHP"
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - name: Login to GitHub Container Registry
        uses: 'docker/login-action@v1'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_REPOSITORY_TOKEN }}

      - name: Set up Depot CLI
        uses: 'depot/setup-action@v1'

      - name: Build and Push Package
        uses: 'depot/build-push-action@v1'
        with:
          project: ${{ secrets.DEPOT_PROJECT_ID }}
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          push: true
          tags: ghcr.io/devgine/composer-php
          context: .
          file: ./Dockerfile

  components:
    needs: build
    runs-on: ubuntu-latest
    name: "Components versions"
    container:
      image: ghcr.io/devgine/composer-php
    steps:
      - name: Composer
        run: composer --version

      - name: PHP
        run: php --version

      - name: PHP Unit
        run: simple-phpunit --version

      - name: PHPStan
        run: rector -V

      - name: PHPStan
        run: phpstan --version

      - name: PHP Code Standard Fixer
        run: php-cs-fixer --version

      - name: PHP Mess Detector
        run: phpmd --version

      - name: PHP Copy Past Detector
        run: phpcpd --version
